### ISSUE TITLE
Ganesha Danu Enastika Processing/Godot Engine/Zulip

### ISSUE THREAD

**Issue by blinfoldking** [gsocindonesia/coaching2018#13]
**Coach assistant:** @wisn 

 **Sanity checks:**

 * [x] GitHub profile photo + detailed profile description

 **Organizations:**

 1. Processing
 2. Godot Engine
 3. Zulip

 **Ideas:**

 | Organization | Idea                               | Difficulty | Technologies & Tools         |
 |-----------------|------------------------------------|------------|------------------------------|
 | Processing  | Classroom management system in p5.js web editor| Intermediate| P5.js, Javascript, Git|
 | Godot Engine| Code Formater| Intermediate| GDscript, C++|
 | Zulip          | Improving Electron Apps | Intermediate | electron, nodejs, javascript|

 **Mentors:**

 1. Processing - Updated hello.p5js.org site: Dan Shiffman <https://www.linkedin.com/in/danielshiffman>
 2. Godot Engine - Code Formater: TBA
 3. Zulip - Improving Electron Apps: Akash Nimare <https://in.linkedin.com/in/akashnimare>

 **Proposals:**

 1. [Processing Proposal](https://docs.google.com/document/d/16NZgkTd2nKxcNrTuQ-cW8DdReIrIg0oKtQx_v4esmE8/edit)
 2. [Godot Proposal](https://docs.google.com/document/d/1uWlcP9eReWW3t6_V9Lvqo1cwZMuzpNoZybYInQvNr4Q/edit) 
 3. TBA

 **Extras:**

 * [x] Personal .github.io website & portfolio: [github web](https://blinfoldking.github.io)

**Comment by jayvdb** [comment]
Processing is a great choice.  Maybe you want to create a Processing demo, e.g. front page for https://github.com/gsocindonesia/gsoc-orgs using its json data.  Lots of logos you could use in a visualisation, or maybe use tags to build a dynamic word cloud.

Also you might be interested in playing with https://github.com/netlify/netlify-cms

**Comment by ceefour** [comment]
@jayvdb is his proposal good?

**Comment by jayvdb** [comment]
@BlinfoldKing , create https://www.openhub.net/accounts/blinfoldking and claim your contributions to important repos. e.g. https://github.com/zulip/zulip-electron/commits?author=BlinfoldKing&since=2018-02-28T17:00:00Z&until=2018-03-27T17:00:00Z

A lot of thought has been put into the Godot proposal.  Great level of detail, and images.  Nice to see.

**Comment by jayvdb** [comment]
coala should have a GDScript bear :-(

**Comment by blinfoldking** [comment]
@jayvdb thanks, GDScript bear would be a great idea, but maybe i should learn more about the core system first

**Comment by ceefour** [comment]
@BlinfoldKing I guess you could let the mentor know you're planning to add a GDScript bear as a _stretch goal_ ...?

**Comment by blinfoldking** [comment]
i don't know whether i could afford to strect the project with GDscript bear with my current skill and understanding, but i'll try consulting with the mentor.

**Comment by ceefour** [comment]
@BlinfoldKing Ok, I think you should focus on what they want/like first. So in this review period you're expected to be active with the mentors, and discuss/refine/clarify points in your proposal. If the mentors have specific contributions they'd like you to do to "prove yourself" then you should try your best to do it.

**Comment by jayvdb** [comment]
See https://github.com/google/gsocguides/pull/24 for clarification on what is expected from students now.
The hard work begins now!

**Comment by jayvdb** [comment]
`https://github.com/repology/repology/issues/598` is a great opportunity to practise skills, and build your resume for next year's gsoc application.
