### ISSUE TITLE
Wisnu Adi Nurcahyo - Haskell.org / coala / Mozilla

### ISSUE THREAD

**Issue by wisn** [gsocindonesia/coaching2018#3]
**Coach assistant:** @wisn

**Sanity checks:**

* [x] GitHub profile photo + detailed profile description
* [x] Initialize proposal
* [x] Writing proposal
* [x] Ask review to mentor
* [x] Finalize proposal
* [x] Submit proposal

**Organizations:**

1. Haskell.org
2. coala
3. Mozilla

**Ideas:**

| Organization | Idea | Difficulty | Technologies & Tools |
| ------------- | ---- | --------- | --------------------- |
| Haskell.org | Format-Preserving YAML | Advanced | Haskell, Stack, YAML, parser, correctness         |
| coala | External Bears Framework in Haskell | Intermediate | Haskell, Stack, coala Bears |
| Mozilla | ... | ... | ... |

**Mentors:**

**Haskell.org - Format-Preserving YAML**

1. Jasper Van der Jeugt <jaspervdj@gmail.com>
2. Tom Sydney Kerckhove <syd.kerckhove@gmail.com>

**External Bears Framework in Haskell**

1. Mario Wenzel <maweki@gmail.com>

**Proposals:**

1. [Haskell.org: Format-Preserving YAML](https://docs.google.com/document/d/1FD9W8MT8CbRBuVP_lFUz-5mqZBuo7nc2yJ8YqrigHSw/edit?usp=sharing)
2. [coala: External Bears Framework in Haskell](https://docs.google.com/document/d/1_iVan1nDn14N-hbnpR76H0LTznj9InE5_G_c6O1LFxM/edit?usp=sharing)
3. TBA

**Extras:**

* [x] OpenHub: https://www.openhub.net/accounts/wisn
* [x] StackOverflow Developer Story: https://stackoverflow.com/story/wisn
* [x] Make a (small) contribution to Haskell project.
* [x] Read some format-preserving tree and parser approaches.
* [ ] Writing article about lexer and parser for proving my competence.
* [x] Add diagram.

**Comment by jayvdb** [comment]
for the Haskell work, in addition to contributing to a core Haskell library, I recommend that you contribute to https://github.com/hercules-team/augeas , a format preserving library.  It has a broken/minimal YAML support, and fixing that is very hard.  However there are easier issues that you can solve in that project.

**Comment by wisn** [comment]
I'm going to contribute to another Haskell project such as [Hakyll](https://github.com/jaspervdj/hakyll).

**Comment by wisn** [comment]
I think I should find another Haskell project as a backup since Hakyll is not really active now.

**Comment by wisn** [comment]
How about [blaze-html](https://github.com/jaspervdj/blaze-html), @jayvdb?

**Comment by jayvdb** [comment]
I think `hakyll` is a much better choice.
`blaze-html` doesnt use yaml, and it is as inactive as hakyll, and has less stars and contributors, and a much lower complexity.

**Comment by wisn** [comment]
Must be something related to YAML? Is parsing related stuff enough? Jasper said what should I do is make a (small) contribution to Haskell project and then read some approach that exists for format-preserving syntax and parser.

**Comment by jayvdb** [comment]
> Must be something related to YAML?

Ideally, yes.

> Is parsing related stuff enough?

'enough' isnt relevant.  hekyll is better for lots of reasons mentioned, and I could give lots of other reasons also.

> Jasper said what should I do is make a (small) contribution to Haskell project 

We'll get to that, later.

> and then read some approach that exists for format-preserving syntax and parser.

https://github.com/gsocindonesia/coaching2018/issues/3#issuecomment-369093531

**Comment by wisn** [comment]
Okay. Gonna contribute to Hakyll then. Will contributes to another project after that one.

**Comment by wisn** [comment]
@jayvdb any advice for my third organization? I would love to use JavaScript.

**Comment by jayvdb** [comment]
> @jayvdb any advice for my third organization? I would love to use JavaScript.

You need to include an application to an organisation with 20+ projects in 2017, such as FOSSASIA, Mozilla, etc.

**Comment by wisn** [comment]
@jayvdb Okay. I think I will try Mozilla.

**Comment by wisn** [comment]
@jayvdb mind to review my proposal? Here [it is](https://docs.google.com/document/d/1FD9W8MT8CbRBuVP_lFUz-5mqZBuo7nc2yJ8YqrigHSw/edit?usp=sharing).

**Comment by ceefour** [comment]
@wisn very good first draft and quite clear. It'd be great if you can share your proposal to telkomuniversity LINE group :)

**Comment by wisn** [comment]
@ceefour okay. Is it all clear? I will mark your comments as resolved.

**Comment by wisn** [comment]
My first proposal draft submitted!

**Comment by wisn** [comment]
@ceefour @jayvdb 
Based on the latest [Haskell Summer of Code blog post](https://summer.haskell.org/news/2018-03-14-student-applications.html), I have added a **motivation** section in my proposal draft.

> Lastly, we recognize that inclusion is an important part of our mission to promote Haskell. Therefore, we strongly encourage applications from people in communities that are underrepresented in functional programming, including but not limited to women; people of color; people in gender, sexual and romantic minorities; people with disabilities; people residing in Asia, Africa, or Latin America; and people who have never taken part in similar programs before.

**Comment by wisn** [comment]
@jayvdb @ceefour My 2nd proposal draft has been submitted. It is [External Bears Framework in Haskell](https://docs.google.com/document/d/1_iVan1nDn14N-hbnpR76H0LTznj9InE5_G_c6O1LFxM/edit?usp=sharing).

**Comment by wisn** [comment]
I will complete the detail section (in the worst case) tomorrow.

**Comment by wisn** [comment]
@jayvdb @ceefour [Format-Preserving YAML](https://docs.google.com/document/d/1FD9W8MT8CbRBuVP_lFUz-5mqZBuo7nc2yJ8YqrigHSw/edit?usp=sharing) now final.

**Comment by wisn** [comment]
@jayvdb @ceefour [External Bears Framework in Haskell](https://docs.google.com/document/d/1_iVan1nDn14N-hbnpR76H0LTznj9InE5_G_c6O1LFxM/edit?usp=sharing) now ready to get some reviews.
