### ISSUE TITLE
Kautsar Tisamawi / LibreOffice / FOSSASIA / Wikimedia Foundation

### ISSUE THREAD

**Issue by katsi14** [gsocindonesia/coaching2018#30]
**Coach assistant:** @wisn 

 **Sanity checks:**

 * [ ] GitHub profile photo + detailed profile description

 **Organizations:**

 1. LibreOffice
 2. FOSSASIA
 3. Wikimedia Foundation

 **Ideas:**

 | Organization | Idea                               | Difficulty | Technologies & Tools         |
 |--------------|------------------------------------|------------|------------------------------|
 | LibreOffice          | Improve and fix  Bugs LibreOffice Android version                              | Medium        | Android, Java, C++                          |
 | FOSSASIA          | Adding Social Media Features                                | Medium        | Android, Java , Android Studio                          |
 | Wikimedia Foundation          | Feedback on how pictures uploaded to Commons get used: statistics, barnstars, light gamification                                | Easy        | Android, Java, RxJava, Kotlin                          |

 **Mentors:**

 1. LibreOffice - Improve and fix  Bugs LibreOffice Android version <vmiklos@collabora.co.uk>
 2. FOSSASIA - Adding Social Media Features [GitHub](https://github.com/mariobehling)
 3. Wikimedia Foundation - Feedback on how pictures uploaded to Commons get used: statistics, barnstars, light gamification [Phabricator](https://phabricator.wikimedia.org/p/maskaravivek/)

 **Proposals:**

 1. [Organization: Proposal title](link to Google Docs)
 2. [Organization: Proposal title](link to Google Docs)
 3. [Organization: Proposal title](link to Google Docs)

 **Extras:**

 * [ ] Personal .github.io website : [GitHub](https://github.com/katsi14)
 * [ ] StackOverflow profile & activities: [title](link)

**Comment by ceefour** [comment]
Hore ada dari GAB02 ✌️

@wisn Mungkin memang sengaja milih mas @wisn ? Jadi peserta bebas memilih ascoach sebenarnya, dengan catatan nanti pas hari mulai coaching, semua asisten tidak ada yg overload, jadi bebannya merata. (+/- 1)

**Comment by wisn** [comment]
Oh oke kalo gitu Pak

**Comment by katsi14** [comment]
Duh maaf sepertinya saya salah lihat mas, pak 😥
I believe i see somewhere that _mas wisn_ is the as-coach of End User Application, but it turns out wrong hehe my bad 😅, then should i change it? or leave it be?

**Comment by wisn** [comment]
Ascoach bebas kok mau pilih siapa aja walaupun gasesuai di daftar juga gapapa.

**Comment by wisn** [comment]
Closed due to resignation.

**Comment by wisn** [comment]
Cc @ceefour
