### ISSUE TITLE
Vian Rasyid Diyatma - Amahi/FOSSASIA/TPF

### ISSUE THREAD

**Issue by vanard** [gsocindonesia/coaching2018#34]
**Coach assistant:** @ridhofadilah  

**Sanity checks:**

* [ ] GitHub profile photo + detailed profile description

**Organizations:**

1. Amahi
2. FOSSASIA
3. The Processing Foundation

**Ideas:**

| Organization | Idea                               | Difficulty | Technologies & Tools         |
|--------------|------------------------------------|------------|------------------------------|
| FOSSASIA          | Open Event Android (Implement full feature set of Organizer Android App for Open Event)                                | ...        | Android, Java                          |
|Amahi          | Android App Improvements                                | ...        | Java, Android                          |
| The Processing Foundation          | Testing and updating mobile functionality                                | Beginner        | Github, Android, Javascript, Java                          |

**Mentors:**

1. FOSSASIA - Project: Open Event Android <email@address.com>
2. Amahi - Android App Improvements: Bogdan Mitrea <email@address.com>
3. Amahi - Android App Improvements: Carlos Puchol <email@address.com>
4. The Processing Foundation - Testing and updating mobile functionality: Kate Hollenbach  <kjhollen@alum.mit.edu>
5. The Processing Foundation - Testing and updating mobile functionality: Lauren McCarthy <laurenleemccarthy@gmail.com>

**Proposals:**

1. [Organization: Proposal title](link to Google Docs)
2. [Organization: Proposal title](link to Google Docs)
3. [Organization: Proposal title](link to Google Docs)

**Extras:**

* [ ] Initial contribution to target organization. Link to PR: ...
* [ ] Personal .github.io website & portfolio: [title](link)
* [ ] StackOverflow profile & activities: [title](link)

**Comment by wisn** [comment]
Halo, @vanard! Sepertinya kamu belum memilih organisasi yang diinginkan. Jika ada kesulitan, mari berdiskusi di issue ini... 😃
