### ISSUE TITLE
Agi Maulana - Catrobat / Open Data Kit / Conversations.im

### ISSUE THREAD

**Issue by AgiMaulana** [gsocindonesia/coaching2018#57]
**Coach assistant:** @ghaisani

**Sanity checks:**

* [ ] GitHub profile photo + detailed profile description

**Organizations:**

1. Catrobat
2. Open Data Kit
3. Conversations.im

**Ideas:**

| Organization | Idea                               | Difficulty | Technologies & Tools         |
|--------------|------------------------------------|------------|------------------------------|
| Catrobat          | ...                                | ...        | ...                          |
| Open Data Kit          | ...                                | ...        | ...                          |
| Conversations.im          | ...                                | ...        | ...                          |

**Mentors:**

1. Organization - Project: Name <email@address.com>
2. Organization - Project: Name <email@address.com>
3. Organization - Project: Name <email@address.com>
4. Organization - Project: Name <email@address.com>
5. Organization - Project: Name <email@address.com>

**Proposals:**

1. [Organization: Proposal title](link to Google Docs)
2. [Organization: Proposal title](link to Google Docs)
3. [Organization: Proposal title](link to Google Docs)

**Extras:**

* [ ] Initial contribution to target organization. Link to PR: ...
* [ ] Personal .github.io website & portfolio: [title](https://github.com/agimaulana)
* [ ] StackOverflow profile & activities: [title](https://stackoverflow.com/users/2741453/agi-maulana)

**Comment by wisn** [comment]
Halo, @AgiMaulana! Sepertinya kamu belum memilih organisasi yang diinginkan. Jika ada kesulitan, mari berdiskusi di issue ini... 😃

**Comment by AgiMaulana** [comment]
hai @ghaisani , seperti yang dibilang mas @wisn saya belum memilih organisasi.. bagaimana cara memilihnya? thanks.

**Comment by ghaisani** [comment]
Hai @AgiMaulana , maaf baru bisa respon..
Untuk memilih organisasi bisa dilihat https://summerofcode.withgoogle.com/organizations/ bisa gunakan filter untuk memilih sesuai bidang yang diinginkan, kalo dirasa pilihan terlalu banyak bisa melalui https://gci-leaders.netlify.com/ (lebih gampang milihnya krn cuma 25 organisasi)
Semoga membantu 😃
