### ISSUE TITLE
Afnizar Nur Ghifari - Elastic

### ISSUE THREAD

**Issue by afnizarnur** [gsocindonesia/coaching2018#60]
**Coach assistant:** @wisn

**Sanity checks:**

* [x] GitHub profile photo + detailed profile description

**Organizations:**

1. [Elastic](https://www.elastic.co/) 
2. ...
3. ...

**Ideas:**

| Organization | Idea                               | Difficulty | Technologies & Tools         |
|--------------|------------------------------------|------------|------------------------------|
| Elastic          | [Kibana, Calendar Visualization and Filtering](https://github.com/elastic/gsoc#kibana_calendar_visualization)                               | Simple        | Node.js, React, Kibana, Elasticsearch                          |
| ...          | ...                                | ...        | ...                          |
| ...          | ...                                | ...        | ...                          |

**Mentors:**

1. Elastic - Kibana, Calendar Visualization and Filtering 
    1. Tim Roes <mail@timroes.de>
    2. Thomas Neirynck <thomas@elastic.co>
    3. Daniel Schneiter <email@address.com>
2. Organization - Project: Name <email@address.com>
3. Organization - Project: Name <email@address.com>

**Proposals:**

1. TBA
2. TBA
3. TBA

**Extras:**

* [ ] Initial contribution to target organization. Link to PR: ...
* [x] Personal website: [afnizarnur.com](https://afnizarnur.com/)
* [x] Portfolio: [Dribbble](https://dribbble.com/afnizarnur)

**Comment by afnizarnur** [comment]
Hi @wisn @jayvdb, would love to hear some advice about [this](https://github.com/elastic/gsoc#kibana_calendar_visualization) project 🙇‍♂️.
Thanks!

**Comment by wisn** [comment]
I'm not expert in UI/UX or design related stuff. However, your first selected project idea should be your "dream project."

**Comment by afnizarnur** [comment]
Well, I guess you know some react things 😬 @wisn  
Still looking for another project to work on, will update it later.

**Comment by wisn** [comment]
Well, yeah. The good thing is that the project looks like React centered.

**Comment by jayvdb** [comment]
Elastic is a great choice of org, as preparation work you do for elastic will also be relevant to many other medium-large orgs.

e.g. Wikimedia uses a few elastic products, and has lots of open issues about them, such as [kibana](https://phabricator.wikimedia.org/search/query/wBFDhIhu5iFS/#R).  It would be quite easy to propose a Kibana project to Wikimedia as your second or third application, re-using the knowledge you've build for your primary application to elastic.
