### ISSUE TITLE
Isa Setiawan Abdurrazaq - Mozilla / Liberhealth / Oppia

### ISSUE THREAD

**Issue by isasetiawan** [gsocindonesia/coaching2018#85]
**Coach assistant:** @probeadd 

**Sanity checks:**

* [ ] GitHub profile photo + detailed profile description

**Organizations:**

1. Mozilla
2. Liberhealth
3. Oppia

**Ideas:**

| Organization | Idea                               | Difficulty | Technologies & Tools         |
|--------------|------------------------------------|------------|------------------------------|
| ...          | ...                                | ...        | ...                          |
| ...          | ...                                | ...        | ...                          |
| ...          | ...                                | ...        | ...                          |

**Mentors:**

1. Mozilla - Autowebcompat : Name <email@address.com>
2. Organization - Project: Name <email@address.com>
3. Organization - Project: Name <email@address.com>
4. Organization - Project: Name <email@address.com>
5. Organization - Project: Name <email@address.com>

**Proposals:**

1. [Organization: Proposal title](link to Google Docs)
2. [Organization: Proposal title](link to Google Docs)
3. [Organization: Proposal title](link to Google Docs)

**Extras:**

* [ ] Initial contribution to target organization. Link to PR: ...
* [ ] Personal .github.io website & portfolio: [title](link)
* [ ] StackOverflow profile & activities: [title](link)

**Comment by wisn** [comment]
Asistennya satu aja Bapak @isasetiawan

**Comment by isasetiawan** [comment]
maap maap
