### ISSUE TITLE
Achmad Choirul Rizal - 

### ISSUE THREAD

**Issue by choirulrzl** [gsocindonesia/coaching2018#87]
**Coach assistant:** @kartininurfalah 
**Sanity checks:**

* [x] GitHub profile photo + detailed profile description

**Organizations:**

1. Wikimedia Foundation
2. CLiPS, The Computational Linguistics & Psycholinguistics Research Group of the University of Antwerp 
3. SymPy

**Ideas:**

| Organization | Idea                               | Difficulty | Technologies & Tools         |
|--------------|------------------------------------|------------|------------------------------|
| Wikimedia Foundation          | Add a spreadsheet interface for modifying multiple pages to the Page Forms extension                                | Easy        | Javascript & PHP                         |
| CLiPS, University of Antwerp          | Data Privacy Protection Algorithms                                | ...        |Python + NLP                         |
| SymPy          | Series expansions                                | Medium        | Python & SymPy                          |

**Mentors:**

1. Wikimedia Foundation - Add a spreadsheet interface for modifying multiple pages to the Page Forms extension: Yaron Koren <yaron57@gmail.com>
2. Wikimedia Foundation - Add a spreadsheet interface for modifying multiple pages to the Page Forms extension: Nischay Nahata <nischayn22@gmail.com>
3. CLiPS, University of Antwerp - Data Privacy Protection Algorithms: Guy De Pauw, Tom De Smedt <clips.gsoc@gmail.com>
4. SymPy - Series Expansion: Leonid Kovalev <leonidvkovalev@gmail.com>
5. Organization - Project: Name <email@address.com>

**Proposals:**

1. [Organization: Proposal title](link to Google Docs)
2. [Organization: Proposal title](link to Google Docs)
3. [Organization: Proposal title](link to Google Docs)

**Extras:**

* [ ] Initial contribution to target organization. Link to PR: ...
* [ ] Personal .github.io website & portfolio: [title](link)
* [ ] StackOverflow profile & activities: [title](link)

**Comment by kartininurfalah** [comment]
Hi, @choirulriz  ! Thanks for choosing me as your ascoach.
Don't forget to select the organization and then take the topic ideas that you want for your issue.

**Comment by kartininurfalah** [comment]
Hi @choirulriz don't forget to contact your mentor, and then update your Github issues.
