### ISSUE TITLE
Muhamad Taufiq Ramadhan - Webpack /  LibreHealth / Open Data Kit

### ISSUE THREAD

**Issue by mtaufiqramadhan** [gsocindonesia/coaching2018#93]
**Coach assistant:** @NoveltyOFD

**Sanity checks:**

* [x] GitHub profile photo + detailed profile description

**Organizations:**

1. Webpack
2. LibreHealth
3. Open Data Kit

**Ideas:**

| Organization | Idea                               | Difficulty | Technologies & Tools         |
|--------------|------------------------------------|------------|------------------------------|
| LibreHealth          | Report Generator                                | -        | Mysql, PHP, Jquery, Html, CSS                          |
| ...          | ...                                | ...        | ...                          |
| ...          | ...                                | ...        | ...                          |

**Mentors:**

1. LibreHealth - Project: Report Generator 
    - Art Eaton <email@address.com>
    - Tony <email@address.com>
    - Terry Hill <email@address.com>
2. Organization - Project: Name <email@address.com>
3. Organization - Project: Name <email@address.com>
4. Organization - Project: Name <email@address.com>
5. Organization - Project: Name <email@address.com>

**Proposals:**

1. [Organization: Proposal title](link to Google Docs)
2. [Organization: Proposal title](link to Google Docs)
3. [Organization: Proposal title](link to Google Docs)

**Extras:**

* [ ] Initial contribution to target organization. Link to PR: ...
* [ ] Personal .github.io website & portfolio: [title](link)
* [ ] StackOverflow profile & activities: [title](link)

**Comment by ceefour** [comment]
(moved to #100)
